book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from book1.views import hello_view, anekdot_view, main_view, book_list_view, book_detail_view, book_create_view, review_create_view
urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello/', hello_view, name="hello_view"),
    path('fun/', anekdot_view, name='anekdot_view'),
    path('', main_view, name='main_view'),
    path('books/', book_list_view, name='book_list_view'),
    path("book/<int:book_id>/", book_detail_view, name='book_detail_view'),
    path("books/create/", book_create_view, name='post_create_view'),
    path("books/create_review/", review_create_view, name='review_create_view'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book1/models.py
from django.db import models


class Tags(models.Model):
    title = models.CharField(max_length=155)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"
        db_table = 'tags'
        ordering = ['title']


class Category(models.Model):
    title = models.TextField()

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        db_table = 'category'
        ordering = ['title']


class Book(models.Model):
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    released = models.IntegerField(null=True, blank=True)
    rate = models.FloatField(null=True, blank=False)
    tag = models.ManyToManyField(Tags, blank=True)
    category = models.ManyToManyField(Category, blank=True)


    def __str__(self):
        return f"{self.title} - {self.released}"

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        db_table = 'book'
        ordering = ['released']



class Review(models.Model):
    text = models.TextField()
    book = models.ManyToManyField(
        Book
    )

    def __str__(self):
        return f"{self.text}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        db_table = 'reviews'
        ordering = ["text"]

templates/books/book_create.html
{% extends 'components/navbar.html' %}


{% block content %}


<h1 class="mt-5" style="text-align: center;">
    Выставить книгу
</h1>

<body style="background-color: chocolate">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" class="btn btn-primary" value="Выставить книгу">
    </form>
</body>

{% endblock %}

templates/books/book_detail.html
{% extends 'components/navbar.html' %}
{% load static %}

{% block content %}
    
    <div class="card" style="background-color: lightgreen">
        <div class="col-md-3">
            <div class="card shadow" style="background-color: aquamarine">
                <img src="{% if book.image %}/media/{{ book.image }}{% else %}{% static 'notfound.webp' %}{% endif %}" class="card-img-top" alt="{{ book.title }}">
                <div class="card-body">
                    <h2 class="card-title">{{ book.title }}</h2>
                    <div class="mb-3">
                        {% for category in book.category.all %}
                        <span class="badge bg-primary">{{ category.title }}</span>
                        {% endfor %}
                    </div>
                    <p class="card-text">{{ book.description }}</p>
                    <div>
                        <h5>Tags:</h5>
                        {% for tag in book.tag.all %}
                        <span class="badge bg-secondary">{{ tag.title }}</span>
                        {% endfor %}
                    </div>
                    <div class="mt-3">
                        <h5>Reviews:</h5>
                        {% for review in book.review_set.all %}
                        <p class="bg-light p-2">{{ review.text }}</p>
                        {% endfor %}
                    </div>
                    <div class="d-flex justify-content-between mt-3">
                        <a href="/books/" class="btn btn-outline-primary btn-sm">Смотреть Книги</a>
                        <a href="/books/create_review/" class="btn btn-outline-secondary btn-sm">Оставить отзыв</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/books/book_list.html
{% extends 'components/navbar.html' %}
{% load static %}

{% block content %}

<body style="background-color: cornflowerblue">
    <h1 class="text-center mt-5 mb-4">Books</h1>
        <div class="container">
            <div class="row justify-content-center">
                {% for book in books %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100 shadow">
                        {% if book.image %}
                            <img src="/media/{{ book.image }}" class="card-img-top" alt="Book Cover">
                        {% else %}
                            <img src="{% static 'notfound.webp' %}" class="card-img-top" alt="Default Cover">
                        {% endif %}
                        <div class="card-body">
                            <h2 class="card-title">{{ book.title }}</h2>
                            {% for category in book.category.all %}
                            <h3 class="card-category">Категория: {{ category.title }}</h3>
                            {% endfor %}
                            <ul class="list-unstyled">
                                {% for tag in book.tag.all %}
                                    <li><span class="badge badge-pill badge-secondary"><a href="/tags/{{ tag.slug }}">{{ tag.title }}</a></span></li>
                                {% endfor %}
                            </ul>
                            <a href="/book/{{ book.id }}" class="btn btn-primary btn-sm">Посмотреть</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
</body>

{% endblock %}

templates/books/create_review.html
{% extends 'components/navbar.html' %}


{% block content %}


<h1 class="mt-5" style="text-align: center;">
    Выставить книгу
</h1>

<body style="background-color: chocolate">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" class="btn btn-primary" value="Поставить Отзыв">
    </form>
</body>

{% endblock %}